const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "Galspic",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/N10HG1s.jpeg",
"https://i.imgur.com/uWvjEGq.jpeg",
"https://i.imgur.com/lft349e.jpeg",
"https://i.imgur.com/M59jCf6.jpeg",
"https://i.imgur.com/4BjstJj.jpeg",
"https://i.imgur.com/MQAp9K8.jpeg",
"https://i.imgur.com/zU55RMe.jpeg",
"https://i.imgur.com/KLVBGhr.jpeg",
"https://i.imgur.com/sZxrhA5.jpeg",
"https://i.imgur.com/K7WRkfE.jpeg",
"https://i.imgur.com/pepmV3r.jpeg",
"https://i.imgur.com/7WFO37c.jpeg",
"https://i.imgur.com/YedyttW.jpeg",
"https://i.imgur.com/cCSjCoE.jpeg",
"https://i.imgur.com/vOCizr6.jpeg",
"https://i.imgur.com/du5WHl6.jpeg",
"https://i.imgur.com/MuAzKfa.jpeg",
"https://i.imgur.com/O58CmLF.jpeg",
"https://i.imgur.com/RKcHKrF.jpeg",
"https://i.imgur.com/aF5KouU.jpeg",
"https://i.imgur.com/srWyn2x.jpeg",
"https://i.imgur.com/A63vhl0.jpeg",
"https://i.imgur.com/fjsRlwY.jpeg",
"https://i.imgur.com/ZZKs7Qv.jpeg",
"https://i.imgur.com/g3KdyYb.jpeg",
"https://i.imgur.com/wMiLwuk.jpeg",
"https://i.imgur.com/2mL5IoY.jpeg",
"https://i.imgur.com/28dY8mW.jpeg",
"https://i.imgur.com/hJOd9NY.jpeg",
"https://i.imgur.com/c6nXgQa.jpeg",
"https://i.imgur.com/FgtXlgb.jpeg",
"https://i.imgur.com/Iy9P5aE.jpeg",
"https://i.imgur.com/shWUNRW.jpeg",
"https://i.imgur.com/EWCTjti.jpeg",
"https://i.imgur.com/eLtWAFg.jpeg",
"https://i.imgur.com/R1elfo7.jpeg",
"https://i.imgur.com/neWgUl4.jpeg",
"https://i.imgur.com/umRwMzz.jpeg",
"https://i.imgur.com/kNkM1qd.jpeg",
"https://i.imgur.com/Zpdn7ET.jpeg",
"https://i.imgur.com/ym1OORx.jpeg",
"https://i.imgur.com/Zu1oTJF.jpeg",
"https://i.imgur.com/onhj60K.jpeg",
"https://i.imgur.com/1fhA64r.jpeg",
"https://i.imgur.com/zABmAza.jpeg",
"https://i.imgur.com/4vIAUt2.jpeg",
"https://i.imgur.com/ZXJMnJn.jpeg",
"https://i.imgur.com/THAUMeN.jpeg",
"https://i.imgur.com/9sOW1FH.jpeg",
"https://i.imgur.com/zf863pm.jpeg",
"https://i.imgur.com/Yn8Xi3B.jpeg",
"https://i.imgur.com/rg0Dkwa.jpeg",
"https://i.imgur.com/HePpscR.jpeg",
"https://i.imgur.com/q6mGqPg.jpeg",
"https://i.imgur.com/wM0QTLV.jpeg",
"https://i.imgur.com/rOQAWKk.jpeg",
"https://i.imgur.com/wwprO0y.jpeg",
"https://i.imgur.com/xUK69xJ.jpeg",
"https://i.imgur.com/5U0ZYhE.jpeg",
"https://i.imgur.com/GoDSk9W.jpeg",
"https://i.imgur.com/tGDiKpC.jpeg",
"https://i.imgur.com/Z76cFCs.jpeg",
"https://i.imgur.com/RPuGYuu.jpeg",
"https://i.imgur.com/S9CzcgS.jpeg",
"https://i.imgur.com/wdawkiK.jpeg",
"https://i.imgur.com/AFOajQu.jpeg",
"https://i.imgur.com/z5Jxxpg.jpeg",
"https://i.imgur.com/rxGC2VY.jpeg",
"https://i.imgur.com/7gpC5fU.jpeg",
"https://i.imgur.com/yoG9Iai.jpeg",
"https://i.imgur.com/QfNhOgI.jpeg",
"https://i.imgur.com/bvvyTHL.jpeg",
"https://i.imgur.com/Qp0heLd.jpeg",
"https://i.imgur.com/jmjC3UZ.jpeg",
"https://i.imgur.com/9BVQjef.jpeg",
"https://i.imgur.com/jjboznh.jpeg",
"https://i.imgur.com/V9zeBlZ.jpeg",
"https://i.imgur.com/UQSuQxE.jpeg",
"https://i.imgur.com/3ndGPJg.jpeg",
"https://i.imgur.com/N4JTDvh.jpeg",
"https://i.imgur.com/FdFYvQF.jpeg",
"https://i.imgur.com/AQpSO9I.jpeg",
"https://i.imgur.com/6zhIu0N.jpeg",
"https://i.imgur.com/TBcKX5x.jpeg",
"https://i.imgur.com/F7xdlLs.jpeg",
"https://i.imgur.com/GSMduDp.jpeg",
"https://i.imgur.com/E89s3Lz.jpeg",
"https://i.imgur.com/riI7usk.jpeg",
"https://i.imgur.com/EQegskp.jpeg",
"https://i.imgur.com/Y1KynXv.jpeg",
"https://i.imgur.com/kU0G82b.jpeg",
"https://i.imgur.com/gqQtIZF.jpeg",
"https://i.imgur.com/2FJ2DUX.jpeg",
"https://i.imgur.com/D3IOjel.jpeg",
"https://i.imgur.com/7CYNS8q.jpeg",
"https://i.imgur.com/VqRiPUM.jpeg",
"https://i.imgur.com/WmNt9Wa.jpeg",
"https://i.imgur.com/6JyZipw.jpeg",
"https://i.imgur.com/kmlKAch.jpeg",
"https://i.imgur.com/zq5nx7d.jpeg",
"https://i.imgur.com/7ApHLNK.jpeg",
"https://i.imgur.com/2DFnZzc.jpeg",
"https://i.imgur.com/X87adUK.jpeg",
"https://i.imgur.com/52LucJ8.jpeg",
"https://i.imgur.com/9JOGo8U.jpeg",
"https://i.imgur.com/PXVjOPN.jpeg",
"https://i.imgur.com/CUKnjoa.jpeg",
"https://i.imgur.com/apLVyBe.jpeg",
"https://i.imgur.com/kHkgLri.jpeg",
"https://i.imgur.com/Lu6n7Co.jpeg",
"https://i.imgur.com/DCHALTx.jpeg",
"https://i.imgur.com/XycAyH3.jpeg",
"https://i.imgur.com/0fQ3UfC.jpeg",
"https://i.imgur.com/AZB9kz1.jpeg",
"https://i.imgur.com/qAFOg8A.jpeg",
"https://i.imgur.com/gjUNoow.jpeg",
"https://i.imgur.com/4b2Viul.jpeg",
"https://i.imgur.com/xOgjaLL.jpeg",
"https://i.imgur.com/KwKkcWi.jpeg",
"https://i.imgur.com/K5sQHpv.jpeg",
"https://i.imgur.com/V31CDtG.jpeg",
"https://i.imgur.com/zVAQUlz.jpeg",
"https://i.imgur.com/y57qTle.jpeg",
"https://i.imgur.com/dQmGnqZ.jpeg",
"https://i.imgur.com/ykbqO3e.jpeg",
"https://i.imgur.com/QobWkxN.jpeg",
"https://i.imgur.com/k8bJk5W.jpeg",
"https://i.imgur.com/8EN4BqQ.jpeg",
"https://i.imgur.com/eFRLjiO.jpeg",
"https://i.imgur.com/c7JgXau.jpeg",
"https://i.imgur.com/Ejfy8ma.jpeg",
"https://i.imgur.com/PvdxuuU.jpeg",
"https://i.imgur.com/r7aQeW2.jpeg",
"https://i.imgur.com/lXFju5S.jpeg",
"https://i.imgur.com/ch2SE84.jpeg",
"https://i.imgur.com/rD3n64j.jpeg",
"https://i.imgur.com/6TnZ7dg.jpeg",
"https://i.imgur.com/JdZwOXg.jpeg",
"https://i.imgur.com/TybDwqW.jpeg",
"https://i.imgur.com/rOF9axU.jpeg",
"https://i.imgur.com/juLbBYF.jpeg",
"https://i.imgur.com/X2KRBTM.jpeg",
"https://i.imgur.com/HRciY88.jpeg",
"https://i.imgur.com/EEgPLac.jpeg",
"https://i.imgur.com/WYnnsQp.jpeg",
"https://i.imgur.com/WXZRclW.jpeg",
"https://i.imgur.com/TKOyzoQ.jpeg",
"https://i.imgur.com/kQJRzmg.jpeg",
"https://i.imgur.com/iJL0rrM.jpeg",
"https://i.imgur.com/tDSkUvp.jpeg",
"https://i.imgur.com/bkaY6b2.jpeg",
"https://i.imgur.com/fnESgSr.jpeg",
"https://i.imgur.com/k1a2Dcj.jpeg",
"https://i.imgur.com/LDS5eRv.jpeg",
"https://i.imgur.com/MMvL2mW.jpeg",
"https://i.imgur.com/V0hbBW4.jpeg",
"https://i.imgur.com/DA6T17L.jpeg",
"https://i.imgur.com/nLWQH63.jpeg",
"https://i.imgur.com/BPrnqVA.jpeg",
"https://i.imgur.com/xQh7Bp5.jpeg",
"https://i.imgur.com/TfnGCBs.jpeg",
"https://i.imgur.com/U9N2ymB.jpeg",
"https://i.imgur.com/iYwe9Fw.jpeg",
"https://i.imgur.com/SCEhNlH.jpeg",
"https://i.imgur.com/6UuYHVu.jpeg",
"https://i.imgur.com/X85d7BA.jpeg",
"https://i.imgur.com/GuoGWda.jpeg",
"https://i.imgur.com/oywejw8.jpeg",
"https://i.imgur.com/ZDNpXig.jpeg",
"https://i.imgur.com/3jXTL3M.jpeg",
"https://i.imgur.com/fxa65Cf.jpeg",
"https://i.imgur.com/PbebTOC.jpeg",
"https://i.imgur.com/kyQac4y.jpeg",
"https://i.imgur.com/AS6yYpp.jpeg",
"https://i.imgur.com/vXfL4cG.jpeg",
"https://i.imgur.com/YJ37tbT.jpeg",
"https://i.imgur.com/gEb9M1N.jpeg",
"https://i.imgur.com/gDD9e1x.jpeg",
"https://i.imgur.com/a7RD1IN.jpeg",
"https://i.imgur.com/mmaG9qN.jpeg",
"https://i.imgur.com/mkXbcYl.jpeg",
"https://i.imgur.com/jxYRV2b.jpeg",
"https://i.imgur.com/KBRNIaA.jpeg",
"https://i.imgur.com/eMLHWjM.jpeg",
"https://i.imgur.com/0ajLRfE.jpeg",
"https://i.imgur.com/pjEOnPD.jpeg",
"https://i.imgur.com/rg3kC2q.jpeg",
"https://i.imgur.com/TG5oq2x.jpeg",
"https://i.imgur.com/eZZAyZE.jpeg",
"https://i.imgur.com/OfEwUWk.jpeg",
"https://i.imgur.com/HMRwjVA.jpeg",
"https://i.imgur.com/CH9C0AS.jpeg",
"https://i.imgur.com/Oefrsh1.jpeg",
"https://i.imgur.com/yYUL5g6.jpeg",
"https://i.imgur.com/hMZVc5w.jpeg",
"https://i.imgur.com/V7uaB9g.jpeg",
"https://i.imgur.com/6hxlF2n.jpeg",
"https://i.imgur.com/C2IgBLp.jpeg",
"https://i.imgur.com/Mu1g7KY.jpeg",
];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: " Gals pp 🥰",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
