const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "Galspicv2",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/xYagEuX.jpeg",
"https://i.imgur.com/9839PKF.jpeg",
"https://i.imgur.com/NaIjYtl.jpeg",
"https://i.imgur.com/E82n5Eq.jpeg",
"https://i.imgur.com/skjG8En.jpeg",
"https://i.imgur.com/duHepRX.jpeg",
"https://i.imgur.com/anOtL32.jpeg",
"https://i.imgur.com/rox9eji.jpeg",
"https://i.imgur.com/VVqULIn.jpeg",
"https://i.imgur.com/LhX9nSO.jpeg",
"https://i.imgur.com/YvoarIa.jpeg",
"https://i.imgur.com/Inf0s4M.jpeg",
"https://i.imgur.com/JgcqOkh.jpeg",
"https://i.imgur.com/KHI9Xgj.jpeg",
"https://i.imgur.com/YRd8zhY.jpeg",
"https://i.imgur.com/5LHRBtv.jpeg",
"https://i.imgur.com/Wlcxyrx.jpeg",
"https://i.imgur.com/6L3ERNm.jpeg",
"https://i.imgur.com/n74mR7h.jpeg",
"https://i.imgur.com/2UGa4dY.jpeg",
"https://i.imgur.com/7FxVknO.jpeg",
"https://i.imgur.com/7MQ0Rhr.jpeg",
"https://i.imgur.com/sM61ZhU.jpeg",
"https://i.imgur.com/Qiqqn3i.jpeg",
"https://i.imgur.com/HcDLcFI.jpeg",
"https://i.imgur.com/B06mCJU.jpeg",
"https://i.imgur.com/6E2g5l6.jpeg",
"https://i.imgur.com/nqClsJt.jpeg",
"https://i.imgur.com/tiknstC.jpeg",
"https://i.imgur.com/83ZpDv8.jpeg",
"https://i.imgur.com/13PVeO6.jpeg",
"https://i.imgur.com/N9AdNzw.jpeg",
"https://i.imgur.com/2y21vvC.jpeg",
"https://i.imgur.com/pVx5Xr0.jpeg",
"https://i.imgur.com/qBB91ow.jpeg",
"https://i.imgur.com/wGNHsoT.jpeg",
"https://i.imgur.com/Kvez01j.jpeg",
"https://i.imgur.com/DPHj3bZ.jpeg",
"https://i.imgur.com/F881flx.jpeg",
"https://i.imgur.com/wp0UR9R.jpeg",
"https://i.imgur.com/VJgDfWs.jpeg",
"https://i.imgur.com/qrHxfJF.jpeg",
"https://i.imgur.com/pwknl6N.jpeg",
"https://i.imgur.com/3Y09cY6.jpeg",
"https://i.imgur.com/9Z0oHSA.jpeg",
"https://i.imgur.com/YAny8YX.jpeg",
"https://i.imgur.com/C5jGZ4r.jpeg",
"https://i.imgur.com/a1Qzq5Q.jpeg",
"https://i.imgur.com/mHalHbW.jpeg",
"https://i.imgur.com/kNM13nI.jpeg",
"https://i.imgur.com/3RFmKIq.jpeg",
"https://i.imgur.com/jrY6Lq6.jpeg",
"https://i.imgur.com/TXlbN6H.jpeg",
"https://i.imgur.com/fPweU5t.jpeg",
"https://i.imgur.com/SNKO1hb.jpeg",
"https://i.imgur.com/MdDWaAz.jpeg",
"https://i.imgur.com/pLUdA37.jpeg",
"https://i.imgur.com/MLVeblS.jpeg",
"https://i.imgur.com/bYxqoNJ.jpeg",
"https://i.imgur.com/pRp4OQ5.jpeg",
"https://i.imgur.com/9bmE7yg.jpeg",
"https://i.imgur.com/FRP4G7K.jpeg",
"https://i.imgur.com/bwKp1MK.jpeg",
"https://i.imgur.com/fx6TJBy.jpeg",
"https://i.imgur.com/JUbxsbg.jpeg",
"https://i.imgur.com/DROPxUY.jpeg",
"https://i.imgur.com/HyJr5M9.jpeg",
"https://i.imgur.com/rjnmuwJ.jpeg",
"https://i.imgur.com/EKwQdW3.jpeg",
"https://i.imgur.com/sbbDo51.jpeg",
"https://i.imgur.com/Cxh4Aib.jpeg",
"https://i.imgur.com/rLVVjm2.jpeg",
"https://i.imgur.com/BTFN0GI.jpeg",
"https://i.imgur.com/bqxs26S.jpeg",
"https://i.imgur.com/hksoNbk.jpeg",
"https://i.imgur.com/E4pHtfC.jpeg",
"https://i.imgur.com/1ii0QS0.jpeg",
"https://i.imgur.com/G5q0Wf5.jpeg",
"https://i.imgur.com/fAJAyBi.jpeg",
"https://i.imgur.com/q0w7fiv.jpeg",
"https://i.imgur.com/UdbC3D6.jpeg",
"https://i.imgur.com/isKRbof.jpeg",
"https://i.imgur.com/tfg2sbN.jpeg",
"https://i.imgur.com/wgr03rk.jpeg",
"https://i.imgur.com/n3Jers2.jpeg",
"https://i.imgur.com/zaJjWtQ.jpeg",
"https://i.imgur.com/486vFxz.jpeg",
"https://i.imgur.com/YjIljyT.jpeg",
"https://i.imgur.com/0OTGg7x.jpeg",
"https://i.imgur.com/u6KYTUx.jpeg",
"https://i.imgur.com/MyCMrIw.jpeg",
"https://i.imgur.com/ph1SwM1.jpeg",
"https://i.imgur.com/RA44fJY.jpeg",
"https://i.imgur.com/iVUMTOm.jpeg",
"https://i.imgur.com/UWX2nqp.jpeg",
"https://i.imgur.com/eY7sk4a.jpeg",
"https://i.imgur.com/9fM2MTR.jpeg",
"https://i.imgur.com/QfDqX8x.jpeg",
"https://i.imgur.com/NJB9oR5.jpeg",
"https://i.imgur.com/KLopVSn.jpeg",
"https://i.imgur.com/0LigZk4.jpeg",
"https://i.imgur.com/fYEQWiF.jpeg",
"https://i.imgur.com/7xVJV3f.jpeg",
"https://i.imgur.com/GyQbJ5d.jpeg",
"https://i.imgur.com/GJ9BiYI.jpeg",
"https://i.imgur.com/sOZBS7w.jpeg",
"https://i.imgur.com/CkJEbbH.jpeg",
"https://i.imgur.com/IeLynox.jpeg",
"https://i.imgur.com/6VR26HF.jpeg",
"https://i.imgur.com/zzeZ8Z4.jpeg",
"https://i.imgur.com/IdrgE12.jpeg",
"https://i.imgur.com/PrFyhXE.jpeg",
"https://i.imgur.com/dU2Lxkg.jpeg",
"https://i.imgur.com/R28KFlD.jpeg",
"https://i.imgur.com/aIXS0sW.jpeg",
"https://i.imgur.com/6obBEok.jpeg",
"https://i.imgur.com/mRrWhhz.jpeg",
"https://i.imgur.com/ArYcEsd.jpeg",
"https://i.imgur.com/oZYom9l.jpeg",
"https://i.imgur.com/CdDssxq.jpeg",
"https://i.imgur.com/bUDtXC8.jpeg",
"https://i.imgur.com/ugPEvIh.jpeg",
"https://i.imgur.com/b5FIvTa.jpeg",
"https://i.imgur.com/R2Tuywi.jpeg",
"https://i.imgur.com/c0ABbCk.jpeg",
"https://i.imgur.com/2nUsmtV.jpeg",
"https://i.imgur.com/PPKKcvy.jpeg",
"https://i.imgur.com/S7XdZEY.jpeg",
"https://i.imgur.com/TlcSKzN.jpeg",
"https://i.imgur.com/hZ4TmT5.jpeg",
"https://i.imgur.com/V51Eqoy.jpeg",
"https://i.imgur.com/SVCJ5AH.jpeg",
"https://i.imgur.com/Ahv1bNf.jpeg",
"https://i.imgur.com/R6el8Um.jpeg",
"https://i.imgur.com/kZJybfh.jpeg",
"https://i.imgur.com/hUKbkz9.jpeg",
"https://i.imgur.com/emPeI6t.jpeg",
"https://i.imgur.com/D89Tpe1.jpeg",
"https://i.imgur.com/iUlEzTI.jpeg",
"https://i.imgur.com/2kyOQn7.jpeg",
"https://i.imgur.com/vvNZ4eS.jpeg",
"https://i.imgur.com/YoQJH5k.jpeg",
"https://i.imgur.com/PcmABaM.jpeg",
"https://i.imgur.com/93dyhWG.jpeg",
"https://i.imgur.com/wnkRmGV.jpeg",
"https://i.imgur.com/BjfR7KN.jpeg",
"https://i.imgur.com/Xe15Jkc.jpeg",
"https://i.imgur.com/hB5gKNv.jpeg",
"https://i.imgur.com/lHn1NfS.jpeg",
"https://i.imgur.com/mwa0jqh.jpeg",
"https://i.imgur.com/5ZTCvjK.jpeg",
"https://i.imgur.com/cd3WK1X.jpeg",
"https://i.imgur.com/NLB5VIL.jpeg",
"https://i.imgur.com/ReH0YaC.jpeg",
"https://i.imgur.com/N9LnL9q.jpeg",
"https://i.imgur.com/FNH1d9P.jpeg",
"https://i.imgur.com/POfHVAi.jpeg",
"https://i.imgur.com/sflTW85.jpeg",
"https://i.imgur.com/4rDhxwp.jpeg",
"https://i.imgur.com/bFjmkpg.jpeg",
"https://i.imgur.com/IZiXgyj.jpeg",
"https://i.imgur.com/LukfLvo.jpeg",
"https://i.imgur.com/2hqspcW.jpeg",
"https://i.imgur.com/G2lSp9R.jpeg",
"https://i.imgur.com/OS8PJt5.jpeg",
"https://i.imgur.com/DZtXoR0.jpeg",
"https://i.imgur.com/G81lJZ0.jpeg",
"https://i.imgur.com/keAOnmh.jpeg",
"https://i.imgur.com/3EDs3HN.jpeg",
"https://i.imgur.com/OzMXfkD.jpeg",
"https://i.imgur.com/y8Y06qt.jpeg",
"https://i.imgur.com/IyM2xNx.jpeg",
"https://i.imgur.com/dEz4JXC.jpeg",
"https://i.imgur.com/CMZTrZr.jpeg",
"https://i.imgur.com/fInwThz.jpeg",
"https://i.imgur.com/4sO6vvT.jpeg",
"https://i.imgur.com/6KXnnuS.jpeg",
"https://i.imgur.com/Ngq12Iu.jpeg",
"https://i.imgur.com/dgd5l2l.jpeg",
"https://i.imgur.com/G7Myv6B.jpeg",
"https://i.imgur.com/kSxDYjL.jpeg",
"https://i.imgur.com/snIL6Z4.jpeg",
"https://i.imgur.com/pHPHSyN.jpeg",
"https://i.imgur.com/eVyXpUP.jpeg",
"https://i.imgur.com/ksTDGdt.jpeg",
"https://i.imgur.com/izVIp09.jpeg",
"https://i.imgur.com/iacjHsa.jpeg",
"https://i.imgur.com/Yb18c0N.jpeg",
"https://i.imgur.com/LPfbYws.jpeg",
"https://i.imgur.com/ZzCXlzO.jpeg",
"https://i.imgur.com/O8F5zED.jpeg",
"https://i.imgur.com/Cp8SVSC.jpeg",
"https://i.imgur.com/NSJflRs.jpeg",
"https://i.imgur.com/hSJTmiV.jpeg",
"https://i.imgur.com/rTqmAkx.jpeg",
"https://i.imgur.com/ne98cq2.jpeg",
"https://i.imgur.com/NGvlCZ5.jpeg",
"https://i.imgur.com/DvJlZAs.jpeg",
"https://i.imgur.com/PpzqqDy.jpeg",
"https://i.imgur.com/mJAYR77.jpeg",
"https://i.imgur.com/nHpRCNR.jpeg",
"https://i.imgur.com/OhUwLlc.jpeg",
"https://i.imgur.com/B45bBXF.jpeg",
"https://i.imgur.com/9LMLsMT.jpeg",
"https://i.imgur.com/Q6dmthC.jpeg",
"https://i.imgur.com/pbvT2VC.jpeg",
"https://i.imgur.com/W72HP3Z.jpeg",
"https://i.imgur.com/hZEedDu.jpeg",
"https://i.imgur.com/TACK4By.jpeg",
"https://i.imgur.com/9XXTrku.jpeg",
"https://i.imgur.com/AUyXEme.jpeg",
"https://i.imgur.com/2Wokj0y.jpeg",
"https://i.imgur.com/e9mKTCe.jpeg",
"https://i.imgur.com/cIe5vYp.jpeg",
"https://i.imgur.com/0hjuCao.jpeg",
"https://i.imgur.com/NLdve0m.jpeg",
"https://i.imgur.com/Xs4Arkf.jpeg",
"https://i.imgur.com/ni5ZTFD.jpeg",
"https://i.imgur.com/KAgQDIC.jpeg",
"https://i.imgur.com/YyccYnn.jpeg",
"https://i.imgur.com/nJouGpQ.jpeg",
"https://i.imgur.com/1Wm73w6.jpeg",
"https://i.imgur.com/b8UFcJ9.jpeg",
"https://i.imgur.com/f3VX9Jm.jpeg",
"https://i.imgur.com/S1XiFqS.jpeg",
"https://i.imgur.com/GKAFrG8.jpeg",
"https://i.imgur.com/Ib6tIRN.jpeg",
"https://i.imgur.com/7wxwgF5.jpeg",
"https://i.imgur.com/VE4SuLv.jpeg",
"https://i.imgur.com/twNk7vV.jpeg",
"https://i.imgur.com/tG6WHUZ.jpeg",
];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: " Gals pp 🥰 V2 ",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
