var mysterious = "Siegfried Sama";
const request = require("request");
const fs = require("fs")
const axios = require("axios")
module.exports.config = {
  name: "ggg",
  version: "3.0.0",
  hasPermssion: 0,
  credits: `${mysterious}`,
  description: "girl to boy slap",
  commandCategory: "...",
  usages: "[tag]",
  cooldowns: 5,
};

module.exports.run = async({ api, event, Threads, global }) => {
  var link = [
"https://i.imgur.com/PTNsTtc.gif",
"https://i.imgur.com/h6WLdP1.gif",
"https://i.imgur.com/BxqWvRH.gif",
"https://i.imgur.com/DdaSATI.gif",
"https://i.imgur.com/rbcvapr.gif",
"https://i.imgur.com/rPiiHsJ.gif",
"https://i.imgur.com/jKMnCKW.gif",
"https://i.imgur.com/UoBL9QI.gif",
"https://i.imgur.com/uGK2h0P.gif",
"https://i.imgur.com/EXAih1d.gif",
"https://i.imgur.com/XL20qPA.gif",
"https://i.imgur.com/5V3236c.gif",
"https://i.imgur.com/TfR7rd3.gif",
"https://i.imgur.com/wG9C15X.gif",
"https://i.imgur.com/tveZQNH.gif",
"https://i.imgur.com/B7DfyrL.gif",
"https://i.imgur.com/ocDhznK.gif",
"https://i.imgur.com/iS8ZK1a.gif",
"https://i.imgur.com/rQliXS3.gif",
"https://i.imgur.com/tIqHEuG.gif",
"https://i.imgur.com/ll09FGw.gif",
"https://i.imgur.com/d0BJaim.gif",
"https://i.imgur.com/dw8jMd2.gif",
"https://i.imgur.com/A5mmnyN.gif",
"https://i.imgur.com/ncD5dNy.gif",
"https://i.imgur.com/WC5m383.gif",
"https://i.imgur.com/mSkZa3g.gif",
"https://i.imgur.com/4qYYuQp.gif",
"https://i.imgur.com/MD6df0X.gif",
"https://i.imgur.com/zDohVhx.gif",
"https://i.imgur.com/eTQIzRs.gif",
"https://i.imgur.com/0nI3sK7.gif",
"https://i.imgur.com/TzbuYIR.gif",
"https://i.imgur.com/7acsRfW.gif",
"https://i.imgur.com/1CsKok6.gif",
"https://i.imgur.com/5ReF09J.gif",
"https://i.imgur.com/F8WsPts.gif",
"https://i.imgur.com/gUS1Cbg.gif",
"https://i.imgur.com/ftmTqJB.gif",
"https://i.imgur.com/fn8CQAe.gif",
"https://i.imgur.com/ZsXF4vf.gif",
"https://i.imgur.com/45dGViB.gif",
"https://i.imgur.com/SVY0FDB.gif",
"https://i.imgur.com/YZObyuL.gif",
"https://i.imgur.com/5iQ6HkL.gif",
"https://i.imgur.com/J1W0lkF.gif",
"https://i.imgur.com/LViP5aN.gif",
"https://i.imgur.com/TENXjQF.gif",
"https://i.imgur.com/MbJyn5P.gif",
"https://i.imgur.com/fvNDNzO.gif",
"https://i.imgur.com/sKP4RZx.gif",
"https://i.imgur.com/LDFA29c.gif",
"https://i.imgur.com/XiDpZlO.gif",
"https://i.imgur.com/kYbTseZ.gif",
"https://i.imgur.com/SCqkiIc.gif",
"https://i.imgur.com/AvFr9B0.gif",
"https://i.imgur.com/nvuU6kh.gif",
"https://i.imgur.com/ydknH3i.gif",
"https://i.imgur.com/icDjmrb.gif",
"https://i.imgur.com/qcYfed8.gif",
"https://i.imgur.com/RnwNODB.gif",
"https://i.imgur.com/ChvSC3J.gif",
"https://i.imgur.com/DKESFBE.gif",
"https://i.imgur.com/URVtrni.gif",
"https://i.imgur.com/ukfshOE.gif",
"https://i.imgur.com/sNoXtNR.gif",
"https://i.imgur.com/XWcSgYi.gif",
"https://i.imgur.com/T4u5HmP.gif",
"https://i.imgur.com/RBekhC9.gif",
"https://i.imgur.com/mMAioPE.gif",
"https://i.imgur.com/0z6hjcU.gif",
"https://i.imgur.com/tqpqAGI.gif",
"https://i.imgur.com/DWA1yUI.gif",
"https://i.imgur.com/CIhZC0a.gif",
"https://i.imgur.com/DKDWhe2.gif",
"https://i.imgur.com/NWZgJNi.gif",
"https://i.imgur.com/5zBpkuq.gif",
"https://i.imgur.com/xCC2gQq.gif",
"https://i.imgur.com/tXPzV7T.gif",
"https://i.imgur.com/lKngtUz.gif",
"https://i.imgur.com/v3UrzMl.gif",
"https://i.imgur.com/uu43A1a.gif",
"https://i.imgur.com/w6qyR69.gif",
"https://i.imgur.com/dmsYAe2.gif",
"https://i.imgur.com/x7xXibM.gif",
"https://i.imgur.com/85qk30z.gif",
"https://i.imgur.com/HkfVUTp.gif",
"https://i.imgur.com/7vmBvZM.gif",
"https://i.imgur.com/9wcRG8I.gif",
"https://i.imgur.com/y9ciD7E.gif",
"https://i.imgur.com/GuTsMHl.gif",
"https://i.imgur.com/nUeISTl.gif",
"https://i.imgur.com/07Mjg4y.gif",
"https://i.imgur.com/LgJPXNh.gif",
"https://i.imgur.com/bMQJXfo.gif",
"https://i.imgur.com/7vBIPPk.gif",
"https://i.imgur.com/kfAxeJO.gif",
"https://i.imgur.com/3IISlED.gif",
"https://i.imgur.com/1QRqCYL.gif",
"https://i.imgur.com/uJVDAox.gif",
"https://i.imgur.com/BVQryrr.gif",
"https://i.imgur.com/Xz1VTHr.gif",
"https://i.imgur.com/CxuAu1J.gif",
"https://i.imgur.com/0kKbnkz.gif",
"https://i.imgur.com/ugXlTv6.gif",
"https://i.imgur.com/yYKPAg9.gif",
"https://i.imgur.com/yT4kLMG.gif",
"https://i.imgur.com/BQXP2ZH.gif",
"https://i.imgur.com/faUpCtq.gif",
"https://i.imgur.com/pqr9lax.gif",
"https://i.imgur.com/poNF5YM.gif",
"https://i.imgur.com/D5xGxrC.gif",
"https://i.imgur.com/ZJ0gVC1.gif",
"https://i.imgur.com/tOUzYGU.gif",
"https://i.imgur.com/qr9Om6K.gif",
];
   var mention = Object.keys(event.mentions);
     let tag = event.mentions[mention].replace("@", "");
    if (!mention) return api.sendMessage("Mention 1 person that you want to f*** you ", threadID, messageID);
   var callback = () => api.sendMessage({body:`╭──────•◈•───────╮\n\n\n 🖕🖕 ${tag}` + `\n\n  এই দেখো , 😎 তোমাকে আমি এইভাবে খেলব চুনা 🥵 🤏\n\n\n╰──────•◈•───────╯`,mentions: [{tag: tag,id: Object.keys(event.mentions)[0]}],attachment: fs.createReadStream(__dirname + "/cache/slap.gif")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/slap.gif"));  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/slap.gif")).on("close",() => callback());
              }
