const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "mim",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [
"https://i.imgur.com/riMo2q4.jpeg",
"https://i.imgur.com/EsVSDvf.jpeg",
"https://i.imgur.com/J43TM5C.jpeg",
"https://i.imgur.com/npq0cee.jpeg",
"https://i.imgur.com/znUMJVO.jpeg",
"https://i.imgur.com/xlo4Xy1.jpeg",
"https://i.imgur.com/nwEJjwP.jpeg",
"https://i.imgur.com/d5JpOzR.jpeg",
"https://i.imgur.com/S4k2kla.jpeg",
"https://i.imgur.com/xUNa273.jpeg",
"https://i.imgur.com/pxoN4tm.jpeg",
"https://i.imgur.com/SyLrp1O.jpeg",
"https://i.imgur.com/f04Rn08.jpeg",
"https://i.imgur.com/dOfPbYi.jpeg",
"https://i.imgur.com/J5lEZKs.jpeg",
"https://i.imgur.com/gV5oB0u.jpeg",
"https://i.imgur.com/ePDk1np.jpeg",
"https://i.imgur.com/65rrnVu.jpeg",
"https://i.imgur.com/YnYatW6.jpeg",
"https://i.imgur.com/x0Lr711.jpeg",
"https://i.imgur.com/ekVzPSx.jpeg",
"https://i.imgur.com/C4my9E6.jpeg",
"https://i.imgur.com/kN8lLqV.jpeg",
"https://i.imgur.com/SfnuV9c.jpeg",
"https://i.imgur.com/gaP7l3I.jpeg",
"https://i.imgur.com/K3Rjjz5.jpeg",
"https://i.imgur.com/uUMBUUT.jpeg",
"https://i.imgur.com/6g3s1P6.jpeg",
"https://i.imgur.com/BQ71z6G.jpeg",
"https://i.imgur.com/gfIQXv2.jpeg",
"https://i.imgur.com/lB1V7zJ.jpeg",
"https://i.imgur.com/t0OaRua.jpeg",
"https://i.imgur.com/mZROUP1.jpeg",
"https://i.imgur.com/b63GBQf.jpeg",
"https://i.imgur.com/TKn3ZNY.jpeg",
"https://i.imgur.com/fn8SK8I.jpeg",
"https://i.imgur.com/PTZJ380.jpeg",
"https://i.imgur.com/n91hYXu.jpeg",
"https://i.imgur.com/dhLuB8l.jpeg",
"https://i.imgur.com/RE7S75s.jpeg",
"https://i.imgur.com/dh78LXh.jpeg",
"https://i.imgur.com/tqEZ2bA.jpeg",
"https://i.imgur.com/HMg2RbK.jpeg",
"https://i.imgur.com/ZfW3i1A.jpeg",
"https://i.imgur.com/9eVXqBI.jpeg",
"https://i.imgur.com/7NcbhSX.jpeg",
"https://i.imgur.com/y3KWpkn.jpeg",
"https://i.imgur.com/uNBslcr.jpeg",
"https://i.imgur.com/95fnfl2.jpeg",
"https://i.imgur.com/i4uJDhJ.jpeg",
"https://i.imgur.com/iAhDoK8.jpeg",
"https://i.imgur.com/4hUdNkG.jpeg",
"https://i.imgur.com/iUU0RM3.jpeg",
"https://i.imgur.com/8Bqwiwe.jpeg",
"https://i.imgur.com/W3dlclO.jpeg",
"https://i.imgur.com/SEGaENO.jpeg",
"https://i.imgur.com/VYyOPs4.jpeg",
"https://i.imgur.com/Rfed5XR.jpeg",
"https://i.imgur.com/IlVMwt9.jpeg",
"https://i.imgur.com/od9yEaC.jpeg",
"https://i.imgur.com/lll5KVY.jpeg",
"https://i.imgur.com/dnjofxQ.jpeg",
"https://i.imgur.com/58MXZMs.jpeg",
"https://i.imgur.com/FjbR3Hk.jpeg",
"https://i.imgur.com/NKeBVUA.jpeg",
"https://i.imgur.com/G2xouHm.jpeg",
"https://i.imgur.com/DR3fjio.jpeg",
"https://i.imgur.com/r36U1Rr.jpeg",
"https://i.imgur.com/4IAZ8fn.jpeg",
"https://i.imgur.com/cl3urcV.jpeg",
"https://i.imgur.com/VV7sO0J.jpeg",
"https://i.imgur.com/CduBnz3.jpeg",
"https://i.imgur.com/93c0xOq.jpeg",
"https://i.imgur.com/iUTfk83.jpeg",
"https://i.imgur.com/Nf3VF66.jpeg",
"https://i.imgur.com/S7w7wsz.jpeg",
"https://i.imgur.com/VHnRaRg.jpeg",
"https://i.imgur.com/4P3t8r7.jpeg",
"https://i.imgur.com/8mUbuAQ.jpeg",
"https://i.imgur.com/x9LMmER.jpeg",
"https://i.imgur.com/iJ7ySX5.jpeg",
"https://i.imgur.com/FZIX7YX.jpeg",
"https://i.imgur.com/uT6q32a.jpeg",
"https://i.imgur.com/1wGyXZS.jpeg",
"https://i.imgur.com/oaRiIOS.jpeg",
"https://i.imgur.com/IgVrFXD.jpeg",
"https://i.imgur.com/HGVAWMw.jpeg",
"https://i.imgur.com/orjxBnN.jpeg",
"https://i.imgur.com/HL9jCLZ.jpeg",
"https://i.imgur.com/ZnAECd6.jpeg",
"https://i.imgur.com/5vVJO1r.jpeg",
"https://i.imgur.com/p62Jhgz.jpeg",
"https://i.imgur.com/Zbw3qgH.jpeg",
"https://i.imgur.com/KgHDtKr.jpeg",
"https://i.imgur.com/um40Qef.jpeg",
"https://i.imgur.com/5jiYLJ3.jpeg",
"https://i.imgur.com/D1UMxH2.jpeg",
"https://i.imgur.com/cRrs3Qn.jpeg",
"https://i.imgur.com/rkTUoDA.jpeg",
"https://i.imgur.com/4ZZKxLq.jpeg",
"https://i.imgur.com/b2qAs2G.jpeg",
"https://i.imgur.com/pIcGbGe.jpeg",
"https://i.imgur.com/QVCg3sU.jpeg",
"https://i.imgur.com/Q9CPpbe.jpeg",
"https://i.imgur.com/ksbfdww.jpeg",
"https://i.imgur.com/JuCA9I6.jpeg",
"https://i.imgur.com/9vjCE9R.jpeg",
"https://i.imgur.com/41cdqQa.jpeg",
"https://i.imgur.com/sOZhfUf.jpeg",
"https://i.imgur.com/lA38WnE.jpeg",
"https://i.imgur.com/PpbqivU.jpeg",
"https://i.imgur.com/22VgX03.jpeg",
"https://i.imgur.com/dyiMedA.jpeg",
"https://i.imgur.com/NvFMHSS.jpeg",
"https://i.imgur.com/bBSnPdx.jpeg",
"https://i.imgur.com/zaVLd3R.jpeg",
"https://i.imgur.com/VFz6WbD.jpeg",
"https://i.imgur.com/SoGvfyp.jpeg",
"https://i.imgur.com/m8BLUBv.jpeg",
"https://i.imgur.com/7bOSaui.jpeg",
"https://i.imgur.com/bSzqqPA.jpeg",
"https://i.imgur.com/wWKZRx8.jpeg",
"https://i.imgur.com/ubqKaUt.jpeg",
"https://i.imgur.com/PxS5A4v.jpeg",
"https://i.imgur.com/Qz2FAx3.jpeg",
"https://i.imgur.com/oV66MKZ.jpeg",
"https://i.imgur.com/us6LTkw.jpeg",
"https://i.imgur.com/XmLxynR.jpeg",
"https://i.imgur.com/O042wne.jpeg",
"https://i.imgur.com/3F4wfm8.jpeg",
"https://i.imgur.com/4sJLoLL.jpeg",
"https://i.imgur.com/mfrFQsx.jpeg",
"https://i.imgur.com/6LUNxVD.jpeg",
"https://i.imgur.com/4LeOtcQ.jpeg",
"https://i.imgur.com/OGuhJZ5.jpeg",
"https://i.imgur.com/pOj92G7.jpeg",
"https://i.imgur.com/vKzO0dE.jpeg",
"https://i.imgur.com/QGEzWZ4.jpeg",
"https://i.imgur.com/LzeJlA8.jpeg",
"https://i.imgur.com/KUbir5F.jpeg",
"https://i.imgur.com/OsVxj8k.jpeg",
"https://i.imgur.com/ikqUNkh.jpeg",
"https://i.imgur.com/GYU2oFV.jpeg",
"https://i.imgur.com/YMAkXh1.jpeg",
"https://i.imgur.com/C63jOy3.jpeg",
"https://i.imgur.com/BmDOWwH.jpeg",
"https://i.imgur.com/J698Yor.jpeg",
"https://i.imgur.com/Ti6vDbr.jpeg",
"https://i.imgur.com/BoXh8z3.jpeg",
"https://i.imgur.com/sSR4nwx.jpeg",
"https://i.imgur.com/OQcEtd8.jpeg",
"https://i.imgur.com/nLJuFEW.jpeg",
"https://i.imgur.com/mzTD68V.jpeg",
"https://i.imgur.com/ZdTkoGD.jpeg",
"https://i.imgur.com/X0MA4QW.jpeg",
"https://i.imgur.com/qUViMUd.jpeg",
"https://i.imgur.com/WgfNfBq.jpeg",
"https://i.imgur.com/KdF7PD4.jpeg",
"https://i.imgur.com/7X1A2a4.jpeg",
"https://i.imgur.com/3TIVZQQ.jpeg",
"https://i.imgur.com/AxQbNdZ.jpeg",
"https://i.imgur.com/d3Q4A8E.jpeg",
"https://i.imgur.com/mVGrVLU.jpeg",
"https://i.imgur.com/hcCo81F.jpeg",
"https://i.imgur.com/qp2kU0n.jpeg",
"https://i.imgur.com/RF1Ypcw.jpeg",
"https://i.imgur.com/eTsH3uL.jpeg",
"https://i.imgur.com/ie1352f.jpeg",
"https://i.imgur.com/QHTO868.jpeg",
"https://i.imgur.com/oYuBtY4.jpeg",
"https://i.imgur.com/9fuA0lk.jpeg",
"https://i.imgur.com/97UsoAP.jpeg",
"https://i.imgur.com/yV2I7LW.jpeg",
"https://i.imgur.com/Hs1Sam5.jpeg",
"https://i.imgur.com/D0K2niF.jpeg",
"https://i.imgur.com/t551iye.jpeg",
"https://i.imgur.com/TMi26t7.jpeg",
"https://i.imgur.com/iVuGpgj.jpeg",
"https://i.imgur.com/Imi0kSi.jpeg",
"https://i.imgur.com/TAMLDAg.jpeg",
"https://i.imgur.com/AeaPM26.jpeg",
"https://i.imgur.com/7d5fW4a.jpeg",
"https://i.imgur.com/6ESWsAx.jpeg",
"https://i.imgur.com/aKlolzX.jpeg",
"https://i.imgur.com/U1ov5v7.jpeg",
"https://i.imgur.com/r0y82p1.jpeg",
"https://i.imgur.com/2V3Z4kS.jpeg",
"https://i.imgur.com/r5Bcz1B.jpeg",
"https://i.imgur.com/5ri8Wmv.jpeg",
"https://i.imgur.com/gQOycAl.jpeg",
"https://i.imgur.com/HBLeI4Q.jpeg",
"https://i.imgur.com/xv9mCZU.jpeg",
"https://i.imgur.com/lTGWUVu.jpeg",
"https://i.imgur.com/OC6YoVB.jpeg",
"https://i.imgur.com/vhAQ1yJ.jpeg",
"https://i.imgur.com/5O4Y0aM.jpeg",
"https://i.imgur.com/64FT6OX.jpeg",
"https://i.imgur.com/ZYgQPXY.jpeg",
"https://i.imgur.com/1JgXa4x.jpeg",
"https://i.imgur.com/UhnDdWj.jpeg",
"https://i.imgur.com/tWhFptu.jpeg",
"https://i.imgur.com/8t1mXfA.jpeg",
"https://i.imgur.com/zhhtdbC.jpeg",
"https://i.imgur.com/o2wTsFL.jpeg",
"https://i.imgur.com/3U0MtPC.jpeg",
"https://i.imgur.com/4yCBwYB.jpeg",
"https://i.imgur.com/jmxW9rg.jpeg",
"https://i.imgur.com/DzLnHAM.jpeg",
"https://i.imgur.com/Wbkae3Y.jpeg",
"https://i.imgur.com/T6fREVU.jpeg",
"https://i.imgur.com/M1em0hl.jpeg",
"https://i.imgur.com/vA3NuAW.jpeg",
"https://i.imgur.com/hcOCMmx.jpeg",
"https://i.imgur.com/8aI49BN.jpeg",
"https://i.imgur.com/xzGtIuP.jpeg",
"https://i.imgur.com/wPu9FxH.jpeg",
"https://i.imgur.com/vlPOfph.jpeg",
"https://i.imgur.com/gA996Yj.jpeg",
"https://i.imgur.com/HzjaJYr.jpeg",];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: "😁😆😸🙊",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
