const fs = require("fs-extra");
const request = require("request");

module.exports.config = {
 name: "ooo",
 version: "1.0.1",
 hasPermssion: 0,
 credits: "BELAL BOTX666",
 description: "bk pp",
 commandCategory: "Random-IMG",
 usages: "bk pp",
 cooldowns: 2,
 dependencies: {
 "request": "",
 "fs-extra": ""
 }
};

module.exports.run = async ({ api, event }) => {
 const imgLinks = [ 
"https://i.imgur.com/ZdIU3mR.jpeg",
"https://i.imgur.com/IErOj32.jpeg",
"https://i.imgur.com/DDZaNVM.jpeg",
"https://i.imgur.com/LOp6Yr2.jpeg",
"https://i.imgur.com/iRybm3D.jpeg",
"https://i.imgur.com/YVcIreO.jpeg",
"https://i.imgur.com/924Baxm.jpeg",
"https://i.imgur.com/A1ZCUNH.jpeg",
"https://i.imgur.com/uEBnXi5.jpeg",
"https://i.imgur.com/D398mjj.jpeg",
"https://i.imgur.com/Xebn86B.jpeg",
"https://i.imgur.com/QCi9SZy.jpeg",
"https://i.imgur.com/0ND2AV6.jpeg",
"https://i.imgur.com/Whfe2ve.jpeg",
"https://i.imgur.com/1e4UTef.jpeg",
"https://i.imgur.com/35Hh23y.jpeg",
"https://i.imgur.com/EC1YqS4.jpeg",
"https://i.imgur.com/eLYCtKl.jpeg",
"https://i.imgur.com/OUzGHzi.jpeg",
"https://i.imgur.com/8n2lJso.jpeg",
"https://i.imgur.com/8FxxSJx.jpeg",
"https://i.imgur.com/Bq0DwmH.jpeg",
"https://i.imgur.com/UgfEYuV.jpeg",
"https://i.imgur.com/fjLJZvc.jpeg",
"https://i.imgur.com/s2xvVLO.jpeg",
"https://i.imgur.com/mp34dqt.jpeg",
"https://i.imgur.com/B9C9mGy.jpeg",
"https://i.imgur.com/VhdrKtr.jpeg",
"https://i.imgur.com/gnGetc2.jpeg",
"https://i.imgur.com/H2jJOr2.jpeg",
"https://i.imgur.com/zcNVIZm.jpeg",
"https://i.imgur.com/YtWp4ny.jpeg",
"https://i.imgur.com/c17Ir7q.jpeg",
"https://i.imgur.com/vl2san3.jpeg",
"https://i.imgur.com/HwBSe4z.jpeg",
"https://i.imgur.com/I4A21cQ.jpeg",
"https://i.imgur.com/0ITFerF.jpeg",
"https://i.imgur.com/JdSDbRU.jpeg",
"https://i.imgur.com/79VxbSK.jpeg",
"https://i.imgur.com/UDrqhMJ.jpeg",
"https://i.imgur.com/1TryC2X.jpeg",
"https://i.imgur.com/5EAblA0.jpeg",
"https://i.imgur.com/LXdRntT.jpeg",
"https://i.imgur.com/Kw8R5xC.jpeg",
"https://i.imgur.com/2W2rg2x.jpeg",
"https://i.imgur.com/yTsvfbZ.jpeg",
"https://i.imgur.com/uyGqGD3.jpeg",
"https://i.imgur.com/oorJQJe.jpeg",
"https://i.imgur.com/9Qr4bEK.jpeg",
"https://i.imgur.com/9kwLqnU.jpeg",
"https://i.imgur.com/kNgmBF1.jpeg",
"https://i.imgur.com/rR1ZS8a.jpeg",
"https://i.imgur.com/wQmhP3p.jpeg",
"https://i.imgur.com/k9uB41C.jpeg",
"https://i.imgur.com/A2I5Tg2.jpeg",
"https://i.imgur.com/FnN5fFC.jpeg",
"https://i.imgur.com/9646Zpn.jpeg",
"https://i.imgur.com/ZJpK9yq.jpeg",
"https://i.imgur.com/tVGFheU.jpeg",
"https://i.imgur.com/PJfT0SJ.jpeg",
"https://i.imgur.com/leNJV0G.jpeg",
"https://i.imgur.com/0vt72f9.jpeg",
"https://i.imgur.com/56AwnL4.jpeg",
"https://i.imgur.com/FkWUXfF.jpeg",
"https://i.imgur.com/9ayO4iK.jpeg",
"https://i.imgur.com/xmG7e5p.jpeg",
"https://i.imgur.com/6nbWPfr.jpeg",
"https://i.imgur.com/HFQZdta.jpeg",
"https://i.imgur.com/2NqIinm.jpeg",
"https://i.imgur.com/Up0zwlk.jpeg",
"https://i.imgur.com/FCE0sUw.jpeg",
"https://i.imgur.com/7i6m9rb.jpeg",
"https://i.imgur.com/kdmhNKy.jpeg",
"https://i.imgur.com/xSWMDaa.jpeg",
"https://i.imgur.com/N6J84ca.jpeg",
"https://i.imgur.com/bAuHrxF.jpeg",
"https://i.imgur.com/2iWPFSc.jpeg",
"https://i.imgur.com/ded995I.jpeg",
"https://i.imgur.com/MDjY2lM.jpeg",
"https://i.imgur.com/eeCs3fO.jpeg",
"https://i.imgur.com/EXbZOei.jpeg",
"https://i.imgur.com/tdUtfNJ.jpeg",
"https://i.imgur.com/04ZW0ky.jpeg",
"https://i.imgur.com/dRNJA46.jpeg",
"https://i.imgur.com/FEtzrO2.jpeg",
"https://i.imgur.com/2RDoni6.jpeg",
"https://i.imgur.com/1P0IbN0.jpeg",
"https://i.imgur.com/whpWV6k.jpeg",
"https://i.imgur.com/08C7qrL.jpeg",
"https://i.imgur.com/lBvXDBO.jpeg",
"https://i.imgur.com/6QtTnIo.jpeg",
"https://i.imgur.com/sFArEm8.jpeg",
"https://i.imgur.com/jrhC21k.jpeg",
"https://i.imgur.com/rJNHVKY.jpeg",
"https://i.imgur.com/2Pm2puJ.jpeg",
"https://i.imgur.com/gx6GIa2.jpeg",
"https://i.imgur.com/c3NffvA.jpeg",
"https://i.imgur.com/cD97OGp.jpeg",
"https://i.imgur.com/UN1XAUd.jpeg",
"https://i.imgur.com/mSSx314.jpeg",
"https://i.imgur.com/pJwXiN3.jpeg",
"https://i.imgur.com/zgLTwmt.jpeg",
"https://i.imgur.com/oAkL0pN.jpeg",
"https://i.imgur.com/zhVsIFg.jpeg",
"https://i.imgur.com/LqKRZKI.jpeg",
"https://i.imgur.com/aJhJrzz.jpeg",
"https://i.imgur.com/Er5QFKw.jpeg",
"https://i.imgur.com/TJnNdld.jpeg",
"https://i.imgur.com/WXoEDcM.jpeg",
"https://i.imgur.com/ZM3LDZy.jpeg",
"https://i.imgur.com/Ie1hWQl.jpeg",
"https://i.imgur.com/61IqkHl.jpeg",
"https://i.imgur.com/O6tZCGe.jpeg",
"https://i.imgur.com/7SSEE6g.jpeg",
"https://i.imgur.com/acQxo2G.jpeg",
"https://i.imgur.com/xQfMjdK.jpeg",
"https://i.imgur.com/nnPr72U.jpeg",
"https://i.imgur.com/ZL1kOyI.jpeg",
"https://i.imgur.com/lobiQjv.jpeg",
"https://i.imgur.com/1Afb0TB.jpeg",
"https://i.imgur.com/oXNLz8m.jpeg",
"https://i.imgur.com/FyFcDlu.jpeg",
"https://i.imgur.com/TrmyDG8.jpeg",
"https://i.imgur.com/PDNsV9l.jpeg",
"https://i.imgur.com/kbskjYa.jpeg",
"https://i.imgur.com/MgkHjLM.jpeg",
"https://i.imgur.com/WXpsl2p.jpeg",
"https://i.imgur.com/ZeSCZLV.jpeg",
"https://i.imgur.com/XeHkOb9.jpeg",
"https://i.imgur.com/ypuGhft.jpeg",
"https://i.imgur.com/bLjY1OF.jpeg",
"https://i.imgur.com/aKX2xah.jpeg",
"https://i.imgur.com/z13u4rw.jpeg",
"https://i.imgur.com/D9Y0KKq.jpeg",
"https://i.imgur.com/pDMnzqT.jpeg",
"https://i.imgur.com/gwje18K.jpeg",
"https://i.imgur.com/OkmUZRy.jpeg",
"https://i.imgur.com/tdTESwk.jpeg",
"https://i.imgur.com/aUyiJeZ.jpeg",
"https://i.imgur.com/wBk2NBs.jpeg",
"https://i.imgur.com/08Kf1vU.jpeg",
"https://i.imgur.com/CIgE7TM.jpeg",
"https://i.imgur.com/uydbhfy.jpeg",
"https://i.imgur.com/7zi9jJr.jpeg",
"https://i.imgur.com/c6mzVsG.jpeg",
"https://i.imgur.com/2WEJHBa.jpeg",
"https://i.imgur.com/cGFSSo7.jpeg",
"https://i.imgur.com/Bl83xI8.jpeg",
"https://i.imgur.com/cea5JUS.jpeg",
"https://i.imgur.com/P6TOjbE.jpeg",
"https://i.imgur.com/7VX0E44.jpeg",
"https://i.imgur.com/nNL2ZDw.jpeg",
"https://i.imgur.com/vusnoGr.jpeg",
"https://i.imgur.com/ALqTvOT.jpeg",
"https://i.imgur.com/mtwLLow.jpeg",
"https://i.imgur.com/D7aQ5sO.jpeg",
"https://i.imgur.com/MaSDYE3.jpeg",
"https://i.imgur.com/sv3n6km.jpeg",
"https://i.imgur.com/nlgux4h.jpeg",
"https://i.imgur.com/HznYg1K.jpeg",
"https://i.imgur.com/Q1lyzHy.jpeg",
"https://i.imgur.com/Ri4KAUL.jpeg",
"https://i.imgur.com/WtmTkeh.jpeg",
"https://i.imgur.com/02lhubT.jpeg",
"https://i.imgur.com/C72Myx7.jpeg",

];

 const selectedImage = imgLinks[Math.floor(Math.random() * imgLinks.length)];
 const filePath = `${__dirname}/cache/fb_boy.jpg`;

 const callback = () => {
 api.sendMessage({
 body: " wow 😳 mal mal 🥵",
 attachment: fs.createReadStream(filePath)
 }, event.threadID, () => fs.unlinkSync(filePath));
 };

 request(encodeURI(selectedImage)).pipe(fs.createWriteStream(filePath)).on("close", callback);
};
